// Auto-generated by scripts/add-bank-logo.mjs. Do not edit by hand.
export interface BankLogoEntry {
  file: string;
  name: string;
}

export const bankLogosManifest: Record<string, BankLogoEntry> = {
  "bancor": {
    "file": "bancor.png",
    "name": "BANCOR"
  },
  "bbva": {
    "file": "bbva.png",
    "name": "BBVA"
  },
  "bica": {
    "file": "bica.png",
    "name": "Banco Bica"
  },
  "bpn": {
    "file": "bpn.png",
    "name": "BPN"
  },
  "brubank": {
    "file": "brubank.png",
    "name": "Brubank"
  },
  "bse": {
    "file": "bse.png",
    "name": "Banco Santiago"
  },
  "buepp": {
    "file": "buepp.png",
    "name": "Buepp"
  },
  "ciudad": {
    "file": "ciudad.png",
    "name": "Ciudad"
  },
  "columbia": {
    "file": "columbia.png",
    "name": "Banco Columbia"
  },
  "comafi": {
    "file": "comafi.png",
    "name": "Comafi"
  },
  "corrientes": {
    "file": "corrientes.png",
    "name": "Banco Corrientes"
  },
  "credicoop": {
    "file": "credicoop.png",
    "name": "Credicoop"
  },
  "delsol": {
    "file": "delsol.png",
    "name": "Banco del Sol"
  },
  "entrerios": {
    "file": "entrerios.png",
    "name": "Banco Entre Rios"
  },
  "galicia": {
    "file": "galicia.png",
    "name": "Galicia"
  },
  "hipotecario": {
    "file": "hipotecario.png",
    "name": "Hipotecario"
  },
  "icbc": {
    "file": "icbc.png",
    "name": "ICBC"
  },
  "lagaceta": {
    "file": "lagaceta.png",
    "name": "Club La Gaceta"
  },
  "macro": {
    "file": "macro.png",
    "name": "Macro"
  },
  "mercado": {
    "file": "mercadopago.png",
    "name": "Mercado Pago"
  },
  "mercadopago": {
    "file": "mercadopago.png",
    "name": "Mercado Pago"
  },
  "modo": {
    "file": "modo.png",
    "name": "Modo"
  },
  "municipal": {
    "file": "municipal.png",
    "name": "Banco Municipal"
  },
  "nacion": {
    "file": "nacion.png",
    "name": "Banco Nación"
  },
  "naranjax": {
    "file": "naranjax.png",
    "name": "NaranjaX"
  },
  "patagonia": {
    "file": "patagonia.png",
    "name": "Patagonia"
  },
  "personal": {
    "file": "personalpay.png",
    "name": "Personal Pay"
  },
  "personalpay": {
    "file": "personalpay.png",
    "name": "Personal Pay"
  },
  "piano": {
    "file": "piano.png",
    "name": "Banco Piano"
  },
  "sanjuan": {
    "file": "sanjuan.png",
    "name": "Banco San Juan"
  },
  "santacruz": {
    "file": "santacruz.png",
    "name": "Banco Santa Cruz"
  },
  "santafe": {
    "file": "santafe.png",
    "name": "Banco Santa Fe"
  },
  "santander": {
    "file": "santander.png",
    "name": "Santander"
  },
  "supervielle": {
    "file": "supervielle.png",
    "name": "Supervielle"
  },
  "yoy": {
    "file": "yoy.png",
    "name": "YOY"
  }
};
