// Auto-generated by scripts/download-bank-logos.mjs. Do not edit by hand.
export interface BankLogoEntry {
  file: string;
  name: string;
}

export const bankLogosManifest: Record<string, BankLogoEntry> = {};
